config/routes.rb
Akodemi::Application.routes.draw do
	resources :users
	resources :sessions, only: [:new, :create, :destroy]
	resources :jobs

	root 'static_pages#home'
	match '/about', 	to: 'static_pages#about', 	via: 'get'

	match '/profile', 	to: 'users#show', 			via: 'get'
	match '/signup', 	to: 'users#new', 			via: 'get'

	match '/signin', 	to: 'sessions#new', 		via: 'get'
	match '/signout', 	to: 'sessions#destroy',		via: 'delete'

	match '/newjob',	to: 'jobs#new',				via: 'post'
end

app/models/job.rb
class Job < ActiveRecord::Base
	# Allow use of attribute name type in database
	self.inheritance_column = nil

	# Validations
	validates :title, presence: true
	validates :title, length: { minimum: 2 }

	validates :type, presence: true

	validates :city, presence: true
	validates :city, length: { minimum: 2 }

	validates :last_day, presence: true

	validates :description, presence: true
	validates :description, length: { maximum: 500 }
	validates :description, length: { minimum: 20 }

end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
	before_create :create_remember_token

	# Validations
	validates :name, presence: true
	validates :email, presence: true
	validates :email, uniqueness: true
	validates :password, length: { minimum: 6 }
	validates :password_confirmation, presence: true
	validates :bio, length: { maximum: 500 }

	validates :name, length: { maximum: 50 }

	# email format validation
	validates :email, email: true

	has_secure_password

	has_attached_file :avatar, style: { large: "120x120", medium: "48x48", thumbnail: "26x26" }
	has_attached_file :cv

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.encrypt(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private

		def create_remember_token
			self.remember_token = User.encrypt(User.new_remember_token)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

	def index
		@jobs = Job.all
	end

	def show
		@job = Job.find(params[:id])
	end

	def new
		@job = Job.new
	end

	def create
		@job = Job.new(job_params)
		if @job.save
			# successfully created job
			flash[:success] = "Jobbet: #{@job.title}, har skapats!"
			redirect_to jobs_path
		else
			# error creating job
			render 'new'
		end
	end

	def edit
	end

	def destroy
	end

	private

		def job_params
			params.require(:job).permit(:title, :description, :city, :last_day, :type)
		end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new

	end

	def create
		user = User.find_by(email: params[:session][:email])
		if user && user.authenticate(params[:session][:password])
			sign_in user
			redirect_to user
		else
			flash.now[:error] = "Ogiltig email/lösenords kombination"
			render 'new'
		end
	end

	def destroy
		sign_out
		redirect_to root_url
	end
	
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	if signed_in?
  		redirect_to current_user
  	end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :signed_in_user, only: [:show, :edit, :destroy]
	before_action :correct_user, only: [:show, :edit, :destroy]

	def index
		redirect_to root_url
	end

	def new
		@user = User.new
	end

	def show
		@user = !params[:id].nil? ? User.find(params[:id]) : current_user
	end

	def edit
	end

	def create
		@user = User.new(user_params)
		if @user.save
			sign_in @user
			flash[:success] = "Welcome to Akodemi!"
			redirect_to @user
		else
			render 'new'
		end
	end

	def destroy
		User.find(params[:id]).destroy
		flash[:success] = "Din profil har tagits bort."
		redirect_to users_url
	end

	private

		def user_params
			params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar, :bio)
		end

		# Before filters

		def signed_in_user
			redirect_to signin_url, notice: "Du måste logga in för att besöka den sidan." unless signed_in?
		end

		def correct_user
			@user = User.find(params[:id])
			redirect_to root_url, notice: "Du har inte åtkomst till den här sidan." unless current_user?(@user)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# Checks if the current page is active
	def is_active?(page_name)
	  	# (params[:action] == page_name) ? "active" : current_page?(page_name)
	  	current_page?(page_name) ? "active" : "inactive"
	end
end

app/helpers/jobs_helper.rb
module JobsHelper

	# Fix this path
	City.data_path = './lib/cities/'

	# Return all the valid job types
	def valid_types
		[['Heltid'], ['Deltid'], ['Extrajobb'], ['Sommarjobb']]
	end

	# Return all the cities in Sweden
	def cities
		City.cities_in_country('SE')
	end

end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		remember_token = user.remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.encrypt(remember_token))
		self.current_user = user
	end

	def sign_out
		current_user.update_attribute(:remember_token, User.encrypt(User.new_remember_token))
		cookies.delete(:remember_token)
		self.current_user = nil
	end

	def signed_in?
		!current_user.nil?
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user?(user)
		user == current_user
	end

	def current_user
		remember_token = User.encrypt(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/jobs/_fields.html.erb
<div class="control-group">
	<%= f.label 'Titel', class: "control-label", for: "inputTitle" %>
	<div class="controls">
		<%= f.text_field :title, id: "inputTitle", placeholder: "Jobbtitel" %>
		<span class="help-inline error-inline">
			<%= @job.errors[:title].first %>
		</span>
	</div>
</div>

<div class="control-group">
	<%= f.label 'Typ', class: "control-label", for: "inputType" %>
	<div class="controls">

		<%= f.select :type, valid_types, id: "inputType" %>
		
		<span class="help-inline error-inline">
			<%= @job.errors[:type].first %>
		</span>
	</div>
</div>

<div class="control-group">
	<%= f.label 'Ort', class: "control-label", for: "inputCity" %>
	<div class="controls">
		<%= f.text_field :city, id: "inputCity", placeholder: "Ort" %>
		<span class="help-inline error-inline">
			<%= @job.errors[:city].first %>
		</span>
	</div>
</div>

<div class="control-group inline-form">
	<%= f.label 'Sista anmälningsdag', class: "control-label", for: "inputDate" %>
	<div class="controls">
		<div class="inline-form">
			<%= f.date_select :last_day, order: [:day, :month, :year], start_year: 2013,  id: "inputDate" %>
		</div>
		<span class="help-inline error-inline">
			<%= @job.errors[:last_day].first %>
		</span>
	</div>
</div>

<div class="control-group inline-form">
	<%= f.label 'Beskrivning', class: "control-label", for: "inputDescription" %>
	<div class="controls">
		<%= f.text_area :description, id: "inputDescription", placeholder: "En beskrivning av tjänsten", maxlength: 500 %>
		<div id="counter" class="counter">500</div>
		<span class="help-inline error-inline">
			<%= @job.errors[:description].first %>
		</span>
	</div>
</div>

app/views/jobs/index.html.erb
<% provide(:title, "Alla jobb") %>

<div class="row">
	<div class="span12">
		<table class="table table-responsive" style="border-collapse: collapse;" data-provides="rowlink">
			<thead>
			<tr>
				<th>Titel</th>
				<th>Typ</th>
				<th>Ort</th>
				<th>Sista dag</th>
				<!-- <th>Beskrivning</th> -->
			</tr>
			</thead>
			<tbody>
				<% @jobs.each_with_index do |job, index| %>
					<tr class="clickable-row" href="<%= job_path(job) %>">
						<td><%= job.title %></td>
						<td><%= job.type %></td> <!-- visar bara siffror -->
						<td><%= job.city %></td>
						<td><%= job.last_day.strftime("%e %b %Y") %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

<%= button_to 'Skapa nytt jobb', newjob_url, class: 'btn' %>

app/views/jobs/new.html.erb
<% provide(:title, "Nytt jobb") %>

<h1>Nytt jobb</h1>

<div class="row">
	<div class="span6 offset2">
		<%= form_for @job, html: { class: "form-horizontal" } do |f| %>
			
			<%= render 'fields', f: f %>

			<%= f.submit 'Skapa nytt jobb', class: "btn btn-primary", id: "form-button" %> 
		<% end %>
	</div>
</div>

app/views/jobs/show.html.erb
<% provide(:title, @job.title) %>

<h1><%= @job.title %></h1>

<div class="row span6 offset3">
	<h3>Typ</h3><%= @job.type %>
	<h3>Ort</h3><%= @job.city %>
	<h3>Sista ansökningsdag</h3><%= @job.last_day %>
	<h3>Beskrivning</h3>
	<p><%= @job.description %></p>

	<%= button_to "Sök jobbet!", '#', class: "btn btn-primary", style: "float: right;" %>
</div>

app/views/layouts/_header.html.erb
<header>
	<div class="navbar navbar-fixed-top navbar-inverse">
		<div class="navbar-inner">
			<%= link_to "Akodemi", root_url, id: 'logo' %>

			<% if signed_in? %>

				<ul class="nav pull-left">
					<li><%= link_to "Om", '/about' %></li>
					<li><%= link_to "Alla jobb", jobs_path %></li>
				</ul>
				<ul class="nav pull-right">
					<li>
						<%= link_to current_user.name, '#', class: "dropdown-toggle", data: { toggle: "dropdown" } %>
						<ul class="dropdown-menu">
							<li><%= link_to "Inställningar", edit_user_path(current_user) %></li>
							<li><%= link_to "Logga ut", signout_path, method: 'delete' %></li>
						</ul>

					</li>
				</ul>

			<% else %>

				<ul class="nav pull-left">
					<li><%= active_link_to "Om", about_path %></li>
					<li><%= active_link_to "Gå med", signup_path %></li>
					<li><%= active_link_to "Alla jobb", jobs_path %></li>
				</ul>
				<ul class="nav pull-right">
					<li><%= active_link_to "Logga in", signin_path %></li>
				</ul> 

			<% end %>

		</div>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Akodemi | <%= yield(:title) %></title>
	  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/header' %>

		<% flash.each do |key, value| %>
			<div class="alert alert-<%= key %>"><%= value %></div>
		<% end %>
		
		<div class="container">
			<%= yield %>
		</div>
		<!-- add footer -->
	</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "Om") %>

<h1>Om</h1>

<div class="row">
	<div class="span8 offset2 center">
		<p>Här kommer det finnas en förklarande text som beskriver vad Akodemi handlar om</p>
	</div>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, 'Välkommen') %>
<div class="row">
	<div class="center hero-unit" id="hero">
		<h1>Välkommen till Akodemi</h1>

		<h2>
			Här kommer det stå en hel del text som beskriver sidan på ett bra
			och förklarande sätt.
		</h2>

		<%= link_to "Gå med!", signup_path, class: "btn btn-large btn-primary" %>
	</div>
</div>

app/views/users/_fields.html.erb
<div class="control-group">
	<%= f.label 'Namn', class: "control-label", for: "inputName" %>
	<div class="controls">
		<%= f.text_field :name, id: "inputName", placeholder: "Ditt namn" %>
		<span class="help-inline error-inline">
			<%= @user.errors[:name].first %>
		</span>
	</div>
</div>
<div class="control-group">
	<%= f.label 'Email', class: "control-label", for: "inputEmail" %>
	<div class="controls">
		<%= f.text_field :email, id: "inputEmail", placeholder: "Din email" %>
		<span class="help-inline error-inline">
			<%= @user.errors[:email].first %>
		</span>
	</div>
</div>
<div class="control-group">
	<%= f.label 'Lösenord', class: "control-label", for: "inputPassword" %>
	<div class="controls">
		<%= f.password_field :password, id: "inputPassword", placeholder: "Ange ett lösenord (minst 6 tecken)" %>
		<span class="help-inline error-inline">
			<%= @user.errors[:password].first %>
		</span>
	</div>
</div>
<div class="control-group">
	<%= f.label 'Bekräfta lösenord', class: "control-label", for: "inputPasswordConf" %>
	<div class="controls">
		<%= f.password_field :password_confirmation, id: "inputPasswordConf", placeholder: "Bekräfta ditt lösenord" %>
		<span class="help-inline error-inline">
			<%= @user.errors[:password_confirmation].first %>
		</span>
	</div>
</div>
<div class="control-group">
	<%= f.label 'En beskrivning av dig själv', class: "control-label", for: "inputBio" %>
	<div class="controls">
		<%= f.text_area :bio, id: "inputBio", placeholder: "En beskrivande text som sammanfattar vem du är och vad du är bra på (max 500 tecken)" %>
	</div>
</div>
<div class="control-group">
	<%= f.label 'Ladda upp en profilbild', class: "control-label", for: "inputAvatar" %>
	<div class="controls">
		<%= f.file_field :avatar, id: "inputAvatar" %>
	</div>
</div>
<div class="control-group">
	<%= f.label 'Ladda upp ditt CV', class: "control-label", for: "inputCV" %>
	<div class="controls">
		<%= f.file_field :cv, id: "inputCV" %>
	</div>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Ändra profil") %>

<h1>Redigera profil</h1>

<div class="row">
	<div class="span8 offset1">
		<%= form_for current_user, html: { class: "form-horizontal" } do |f| %>

			<%= render 'fields', f: f %>
			<%= f.submit 'Spara ändringar', class: "btn btn-primary", id: "form-button" %> 
		<% end %>
		<%= button_to 'Ta bort min profil', current_user, method: :delete, style: "float: left;" ,class: "btn btn-danger", data: { confirm: "Är du säker på att du vill ta bort din profil?" } %>
	</div>
</div>

app/views/users/new.html.erb
<% provide(:title, "Gå med") %>

<h1>Gå med i Akodemi</h1>

<div class="row">
	<div class="span6 offset2">

		<%= form_for @user, html: { class: "form-horizontal" } do |f| %>

			<%= render 'fields', f: f %>
			<%= f.submit 'Gå med!', class: "btn btn-primary", id: "form-button" %> 

		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row">
	<aside class="span3">
		<section>
			<%= image_tag @user.avatar.url %> </br>
			<h3>
				<%= current_user.name %>
			</h3>

			<%= current_user.email %> </br>

			<%= button_to "Ändra profil", edit_user_path(current_user), method: 'get', class: 'btn' , style: "margin-top: 10px" %>
		</section>
	</aside>
	<div class="span9">
		<p>Här kommer det visas en lista av passande jobb.</p>
	</div>
</div>